### ISSUE TITLE
Allow to only receive resampling indices (make hierarch agnostic to specific statistical tests).

### ISSUE THREAD

**Issue by JohannesWiesner** [rishi-kulkarni/hierarch#127]
I am currently working with data from the Human Connectome Project. The dataset contains a lot of siblings, sometimes even dizygotic or even monozygotic twins. Basically for all my statistical tests, I would have to consider this nested structure when computing p-values (which I would like to derive from permutation test) or confidence intervals (which I would like to obtain from bootstrapping tests). This is how the demographic data would look like:

![image](https://user-images.githubusercontent.com/48254290/217231196-869663cd-5ab9-4ed6-a1a9-0480f3398b20.png)

The problem is, that I would like to conduct multivariate tests (i.e. CCA to be more specific). Which means that besides from the demographic information that could be used to conduct a hierarchical resampling procedure, I also have matrices  `X`  and `y` that contain the "actual data" and that I would use to perform my statistical test. When looking at the [Hypothesis Testing section](https://hierarch.readthedocs.io/en/stable/user/hypothesis.html#), I can see that hierarch currently seems to be restricted to simple univariate tests like t-tests and ANOVA? Do you think it would be feasible to allow users to only obtain resampled indices so they could apply their own tests?

This is my current approach which is quite tedious:
1.) Use [FSL-Palm](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/PALM) to derive [exchangability blocks](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/PALM/ExchangeabilityBlocks) using the [hcp2blocks.m](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/PALM/ExchangeabilityBlocks#EBs_for_data_of_the_Human_Connectome_Project) function 
2.) Use a [python implementation](https://github.com/jameschapman19/scikit-palm) of FSL-Palm's quicker function (`skpalm.permutations.quickperms`) to derive a matrix of reampled indices.

**Comment by rishi-kulkarni** [comment]
Many thanks for your note @JohannesWiesner!

You raise an interesting and quite useful question, which would ideally be very straightforward to implement - I could expose the helper function the `hypothesis_test` function uses to generate resampled datasets. I assume with that, you should be able to perform your desired analysis, right?

**Comment by JohannesWiesner** [comment]
Yup, that should do the trick! :)

**Comment by rishi-kulkarni** [comment]
I'll take a crack at this over the next few weekends - hopefully it is going to be as simple as I hope.

**Comment by JohannesWiesner** [comment]
Any update on this? Still could use the bootstrapping implementation from hierarch :) AFAIK FSL Palm does not offer drawing with replacement.

**Comment by jameschapman19** [comment]
@rishi-kulkarni thought I'd just comment to say I work on similar problems to @JohannesWiesner and agree there would be a lot of value to exposing the function to generate the indices to the extent it adds helpful motivation :)

Nice work on this package!

**Comment by rishi-kulkarni** [comment]
Hi @JohannesWiesner @jameschapman19 

This took a little more thinking than I expected, as we want to handle situations where there are different number of observations per treatment group (as is common with biological datasets). 

All that said, I ended up deciding to create a generator that yields resampled datasets rather than the resampled indexes, to provide full transparency into which obs are associated with which resampled treatment group. Please open another issue if you notice any bugs with this function!
